export type Tab = "Dashboard" | "Subscriptions" | "Insights" | "Settings";

export const categories = [
  "Streaming",
  "Music",
  "Software",
  "Cloud",
  "Gaming",
  "Fitness",
  "Finance",
  "Utilities",
  "Education",
  "Other",
];

export const symbols: Record<string, string> = {
  EUR: "€",
  USD: "$",
  JPY: "¥",
  BGN: "лв",
  CZK: "Kč",
  DKK: "kr",
  GBP: "£",
  HUF: "Ft",
  PLN: "zł",
  RON: "lei",
  SEK: "kr",
  CHF: "Fr",
  ISK: "kr",
  NOK: "kr",
  HRK: "kn",
  RUB: "₽",
  TRY: "₺",
  AUD: "$",
  BRL: "R$",
  CAD: "$",
  CNY: "¥",
  HKD: "HK$",
  IDR: "Rp",
  ILS: "₪",
  INR: "₹",
  KRW: "₩",
  MXN: "Mex$",
  MYR: "RM",
  NZD: "NZ$",
  PHP: "₱",
  SGD: "S$",
  THB: "฿",
  ZAR: "R",
};

export const currencies = [
  { code: "EUR", name: "Euro", symbol: "€" },
  { code: "USD", name: "US Dollar", symbol: "$" },
  { code: "JPY", name: "Japanese Yen", symbol: "¥" },
  { code: "BGN", name: "Bulgarian Lev", symbol: "лв" },
  { code: "CZK", name: "Czech Republic Koruna", symbol: "Kč" },
  { code: "DKK", name: "Danish Krone", symbol: "kr" },
  { code: "GBP", name: "British Pound Sterling", symbol: "£" },
  { code: "HUF", name: "Hungarian Forint", symbol: "Ft" },
  { code: "PLN", name: "Polish Zloty", symbol: "zł" },
  { code: "RON", name: "Romanian Leu", symbol: "lei" },
  { code: "SEK", name: "Swedish Krona", symbol: "kr" },
  { code: "CHF", name: "Swiss Franc", symbol: "Fr" },
  { code: "ISK", name: "Icelandic Króna", symbol: "kr" },
  { code: "NOK", name: "Norwegian Krone", symbol: "kr" },
  { code: "HRK", name: "Croatian Kuna", symbol: "kn" },
  { code: "RUB", name: "Russian Ruble", symbol: "₽" },
  { code: "TRY", name: "Turkish Lira", symbol: "₺" },
  { code: "AUD", name: "Australian Dollar", symbol: "$" },
  { code: "BRL", name: "Brazilian Real", symbol: "R$" },
  { code: "CAD", name: "Canadian Dollar", symbol: "$" },
  { code: "CNY", name: "Chinese Yuan", symbol: "¥" },
  { code: "HKD", name: "Hong Kong Dollar", symbol: "HK$" },
  { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp" },
  { code: "ILS", name: "Israeli New Sheqel", symbol: "₪" },
  { code: "INR", name: "Indian Rupee", symbol: "₹" },
  { code: "KRW", name: "South Korean Won", symbol: "₩" },
  { code: "MXN", name: "Mexican Peso", symbol: "Mex$" },
  { code: "MYR", name: "Malaysian Ringgit", symbol: "RM" },
  { code: "NZD", name: "New Zealand Dollar", symbol: "NZ$" },
  { code: "PHP", name: "Philippine Peso", symbol: "₱" },
  { code: "SGD", name: "Singapore Dollar", symbol: "S$" },
  { code: "THB", name: "Thai Baht", symbol: "฿" },
  { code: "ZAR", name: "South African Rand", symbol: "R" },
] as const;

export const currencyCodes: string[] = currencies.map((currency) => currency.code);
