import { Platform, StyleSheet, type TextStyle } from "react-native";

export const styles = StyleSheet.create({
  safe: { flex: 1 },
  screenHost: { flex: 1 },
  loading: { flex: 1, alignItems: "center", justifyContent: "center", gap: 12 },
  loadingText: { fontSize: 14 },
  shell: {
    flex: 1,
    alignSelf: "center",
    width: "100%",
    maxWidth: Platform.select({ web: 1080, default: 680 }),
  },
  content: { flex: 1 },
  screen: {
    padding: Platform.select({ web: 32, default: 20 }),
    paddingBottom: 36,
    gap: 12,
  },
  loginShell: { flex: 1 },
  loginScreen: {
    flexGrow: 1,
    justifyContent: "center",
    padding: 24,
    paddingBottom: 36,
    gap: 32,
  },
  loginBrand: { alignItems: "center" },
  loginLogo: { width: 96, height: 96, borderRadius: 22, marginBottom: 18 },
  loginTitle: { fontSize: 34, fontWeight: "800" },
  loginSubtitle: { maxWidth: 320, textAlign: "center", fontSize: 15, lineHeight: 22, marginTop: 10 },
  loginActions: { width: "100%", maxWidth: 360, alignSelf: "center", gap: 12 },
  loginPrimaryButton: {
    minHeight: 52,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 16,
  },
  loginPrimaryButtonText: { color: "#FFFFFF", fontSize: 16, fontWeight: "800" },
  loginSecondaryButton: {
    minHeight: 52,
    borderRadius: 14,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 16,
  },
  loginSecondaryButtonText: { fontSize: 16, fontWeight: "800" },
  topRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 12 },
  titleLockup: { flexDirection: "row", alignItems: "center", gap: 10 },
  headerLogo: { width: 34, height: 34, borderRadius: 8 },
  headerActionSpacer: { width: 44, height: 44 },
  greeting: { fontSize: 14, fontWeight: "500", marginBottom: 3 },
  title: { fontSize: 28, fontWeight: "700", letterSpacing: 0 },
  addCircle: { width: 44, height: 44, borderRadius: 14, alignItems: "center", justifyContent: "center" },
  totalCard: { borderRadius: 22, padding: 20, marginBottom: 8 },
  totalEyebrow: { color: "#BFDBFE", fontSize: 12, fontWeight: "700", letterSpacing: 1 },
  total: { color: "#fff", fontSize: 36, fontWeight: "700", letterSpacing: -1, marginTop: 8 },
  totalFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 17,
    alignItems: "flex-end",
    gap: 12,
  },
  totalSub: { color: "#DBEAFE", fontSize: 13, flex: 1 },
  totalRemainingStack: { alignItems: "flex-end", flexShrink: 1 },
  totalRemainingValue: { color: "#fff", fontSize: 13, fontWeight: "700" },
  totalRemainingLabel: { color: "#DBEAFE", fontSize: 11, fontWeight: "600", marginTop: 3, textAlign: "right" },
  sectionHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 13, marginBottom: 1 },
  sectionTitle: { fontSize: 18, fontWeight: "700" },
  sectionAction: { fontSize: 14, fontWeight: "600" },
  card: { borderWidth: 1, borderRadius: 18, overflow: "hidden" },
  subscriptionStack: { gap: 12 },
  renewalRow: {
    minHeight: 74,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 12,
    borderWidth: 1,
    borderRadius: 14,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.24,
    shadowRadius: 12,
    elevation: 6,
  },
  subscriptionRow: {
    minHeight: 74,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 12,
    borderWidth: 1,
    borderRadius: 14,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.24,
    shadowRadius: 12,
    elevation: 6,
  },
  lastSubscriptionPill: { marginBottom: 0 },
  iconBadge: { width: 44, height: 44, borderRadius: 13, alignItems: "center", justifyContent: "center" },
  rowText: { flex: 1 },
  rowName: { fontSize: 16, fontWeight: "600" },
  rowMeta: { fontSize: 13, marginTop: 3 },
  rowPrice: { fontSize: 15, fontWeight: "700", textAlign: "right" },
  priceStack: { alignItems: "flex-end" },
  renewalStatus: { fontSize: 12, marginTop: 4 },
  removeButton: { marginLeft: 3, padding: 4 },
  removeConfirmActions: { flexDirection: "row", gap: 4, marginLeft: 3 },
  removeConfirmButton: { padding: 4 },
  summary: { flexDirection: "row", gap: 10, alignItems: "center", padding: 15, borderRadius: 16, marginTop: 8 },
  summaryText: { fontSize: 13, flex: 1, lineHeight: 18 },
  chips: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 4 },
  subscriptionToolbar: { flexDirection: "row", alignItems: "flex-start", gap: 10, marginBottom: 4 },
  subscriptionFilterChips: { flex: 1, flexDirection: "row", flexWrap: "wrap", gap: 8 },
  sortButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  chip: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 999 },
  chipText: { fontSize: 14, fontWeight: "600" },
  empty: { alignItems: "center", padding: 28, borderWidth: 1, borderRadius: 18 },
  emptyTitle: { fontSize: 17, fontWeight: "700", marginTop: 12 },
  emptyText: { textAlign: "center", fontSize: 14, lineHeight: 20, marginTop: 6 },
  emptyButton: { marginTop: 18, paddingHorizontal: 16, height: 42, justifyContent: "center", borderRadius: 12 },
  emptyButtonText: { color: "#fff", fontWeight: "700" },
  metricGrid: { flexDirection: "row", gap: 12, marginTop: 12, marginBottom: 10 },
  metricGridCompact: { flexWrap: "wrap" },
  metric: { flex: 1, borderWidth: 1, borderRadius: 18, padding: 16 },
  metricCompact: { flexBasis: "47%", minWidth: 0 },
  metricLabel: { fontSize: 13 },
  metricValue: { fontSize: 21, fontWeight: "700", marginTop: 7 },
  pieBreakdown: {
    padding: 16,
    gap: 18,
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "center",
  },
  pieChartWrap: {
    width: 224,
    height: 224,
    alignItems: "center",
    justifyContent: "center",
  },
  pieCenter: {
    position: "absolute",
    width: 98,
    height: 98,
    borderRadius: 49,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  pieCenterLabel: { fontSize: 12, fontWeight: "800", marginBottom: 4 },
  pieCenterValue: { maxWidth: 82, fontSize: 14, fontWeight: "800", textAlign: "center" },
  pieSubscriptionList: { flex: 1, minWidth: 240, maxHeight: 276 },
  pieSubscriptionListContent: { gap: 10, paddingRight: 2 },
  pieSubscriptionRow: {
    minHeight: 64,
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  pieSelectionAccent: { width: 6, alignSelf: "stretch", borderRadius: 99 },
  pieSelectionTitle: { fontSize: 15, fontWeight: "800" },
  pieSelectionPrice: { fontSize: 14, fontWeight: "800", textAlign: "right", flexShrink: 0 },
  pieLegendMeta: { fontSize: 12, marginTop: 2 },
  pieShowMoreButton: {
    minHeight: 42,
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  pieShowMoreText: { fontSize: 14, fontWeight: "800" },
  calendarCard: { padding: 12, gap: 10 },
  calendarHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  calendarMonth: { flex: 1, fontSize: 15, fontWeight: "800", textAlign: "center" },
  calendarArrowButton: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  calendarWeekHeader: { flexDirection: "row", gap: 6 },
  calendarWeekday: { flex: 1, fontSize: 11, fontWeight: "800", textAlign: "center" },
  calendarGrid: { gap: 6 },
  calendarWeek: { flexDirection: "row", gap: 6 },
  calendarDay: {
    flex: 1,
    minHeight: 76,
    borderWidth: 1,
    borderRadius: 10,
    padding: 5,
    gap: 4,
  },
  calendarSelectedDay: { borderWidth: 2, padding: 4 },
  calendarDayNumber: { fontSize: 11, fontWeight: "800" },
  calendarCountBadge: {
    minWidth: 24,
    height: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    marginTop: 9,
    paddingHorizontal: 6,
  },
  calendarCountText: { color: "#FFFFFF", fontSize: 12, fontWeight: "800" },
  calendarSelection: { borderTopWidth: 1, paddingTop: 12, gap: 10 },
  calendarSelectionTitle: { fontSize: 15, fontWeight: "800" },
  calendarSelectionEmpty: { fontSize: 13, fontWeight: "600" },
  calendarSubscriptionRow: {
    minHeight: 64,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 10,
    borderRadius: 14,
  },
  calendarSubscriptionAccent: { width: 5, alignSelf: "stretch", borderRadius: 99 },
  calendarSubscriptionName: { fontSize: 15, fontWeight: "700" },
  calendarSubscriptionMeta: { fontSize: 13, marginTop: 3 },
  calendarSubscriptionPrice: { fontSize: 15, fontWeight: "800", textAlign: "right" },
  settingsLabel: { marginTop: 12, marginBottom: -2, fontSize: 12, fontWeight: "700", letterSpacing: 0.8 },
  settingsSectionHeader: {
    minHeight: 54,
    paddingHorizontal: 15,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  settingsSectionTitle: { flex: 1, fontSize: 16, fontWeight: "800" },
  settingsSectionBody: { borderTopWidth: StyleSheet.hairlineWidth },
  settingRow: { flexDirection: "row", padding: 15, gap: 12, alignItems: "center" },
  settingOption: { padding: 15, gap: 12 },
  accountHeader: { flexDirection: "row", alignItems: "center", gap: 12 },
  authButtons: { flexDirection: "row", gap: 10 },
  authButton: { flex: 1, minHeight: 44, borderRadius: 12, alignItems: "center", justifyContent: "center", paddingHorizontal: 12 },
  authButtonText: { fontSize: 14, fontWeight: "700", textAlign: "center" },
  primaryButtonText: { color: "#fff", fontSize: 14, fontWeight: "700", textAlign: "center" },
  textButton: { alignSelf: "center", minHeight: 32, justifyContent: "center", paddingHorizontal: 10 },
  textButtonText: { fontSize: 14, fontWeight: "700" },
  statusText: { fontSize: 13, lineHeight: 18 },
  statusPill: { alignSelf: "flex-start", borderRadius: 999, paddingHorizontal: 10, paddingVertical: 5, marginTop: 2 },
  statusPillText: { fontSize: 12, fontWeight: "700" },
  toastOverlay: {
    position: "absolute",
    left: 16,
    right: 16,
    bottom: 18,
    alignItems: "center",
    zIndex: 1000,
    elevation: 1000,
  },
  toast: {
    maxWidth: 420,
    minHeight: 42,
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 11,
    justifyContent: "center",
    shadowColor: "#000000",
    shadowOpacity: 0.18,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 5,
  },
  toastText: { fontSize: 14, fontWeight: "800", textAlign: "center" },
  syncButton: {
    minHeight: 44,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 14,
  },
  syncButtonText: { fontSize: 14, fontWeight: "800" },
  encryptionCard: {
    borderRadius: 14,
    borderWidth: 1,
    padding: 14,
    gap: 12,
  },
  encryptionHeader: { flexDirection: "row", alignItems: "flex-start", gap: 12 },
  encryptionIcon: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  encryptionActions: {
    flexDirection: Platform.select({ web: "row", default: "column" }),
    gap: 10,
  },
  encryptionButton: {
    flex: 1,
    minHeight: 44,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  encryptionButtonContent: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 },
  encryptionButtonText: { fontSize: 14, fontWeight: "800", textAlign: "center" },
  encryptionModalOverlay: {
    flex: 1,
    justifyContent: "center",
    padding: 20,
    backgroundColor: "rgba(0,0,0,0.42)",
  },
  encryptionModalPanel: {
    width: "100%",
    maxWidth: 460,
    alignSelf: "center",
    borderRadius: 22,
    borderWidth: 1,
    padding: 20,
    gap: 14,
    shadowColor: "#000000",
    shadowOpacity: 0.22,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 12 },
    elevation: 10,
  },
  encryptionModalTitleRow: { flexDirection: "row", alignItems: "center", gap: 12 },
  encryptionModalTitle: { flex: 1, fontSize: 20, fontWeight: "900" },
  encryptionModalClose: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  encryptionWarning: {
    borderRadius: 14,
    borderWidth: 1,
    padding: 12,
    flexDirection: "row",
    gap: 10,
  },
  encryptionWarningText: { flex: 1, fontSize: 13, lineHeight: 18, fontWeight: "600" },
  encryptionFieldStack: { gap: 10 },
  encryptionInput: {
    minHeight: 48,
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 14,
    fontSize: 15,
    fontWeight: "700",
  },
  encryptionRememberRow: {
    minHeight: 58,
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  encryptionModalActions: { flexDirection: "row", gap: 10, marginTop: 2 },
  encryptionStatusPanel: {
    width: "100%",
    maxWidth: 360,
    alignSelf: "center",
    borderRadius: 18,
    borderWidth: 1,
    padding: 22,
    alignItems: "center",
    gap: 12,
    shadowColor: "#000000",
    shadowOpacity: 0.22,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 12 },
    elevation: 12,
  },
  encryptionStatusTitle: { fontSize: 18, fontWeight: "900", textAlign: "center" },
  encryptionStatusText: { fontSize: 13, fontWeight: "700", textAlign: "center" },
  comingSoon: { fontSize: 12, fontWeight: "600" },
  paydayInput: { minHeight: 46, borderRadius: 12, paddingHorizontal: 14, fontSize: 16, fontWeight: "700" },
  colorPresetGrid: { flexDirection: "row", flexWrap: "wrap", gap: 9 },
  settingsColorPreset: {
    width: 36,
    height: 36,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  colorPresetInputRow: { flexDirection: "row", gap: 10 },
  colorPresetInput: {
    flex: 1,
    minHeight: 44,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 12,
    fontSize: 15,
    fontWeight: "700",
  },
  colorPresetAddButton: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  currencyGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  currencyOption: {
    width: "31%",
    minWidth: 0,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 9,
    gap: 3,
  },
  currencyOptionHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 6 },
  currencyOptionCode: { fontSize: 13, fontWeight: "800" },
  currencyOptionName: { fontSize: 11, fontWeight: "600" },
  privacyHeader: { flexDirection: "row", alignItems: "center", gap: 14, marginBottom: 4 },
  privacyBackButton: {
    width: 42,
    height: 42,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  privacyIntro: { padding: 16 },
  privacySection: { gap: 8, marginTop: 12 },
  privacyBody: { fontSize: 14, lineHeight: 21 },
  reminderTimeRow: {
    minHeight: 46,
    borderRadius: 12,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  reminderTimeInput: { flex: 1, minHeight: 46, fontSize: 16, fontWeight: "700" },
  dangerRow: { flexDirection: "row", gap: 12, padding: 16, borderRadius: 18, borderWidth: 1, alignItems: "center" },
  dangerText: { color: "#DC2626", fontSize: 16, fontWeight: "600" },
  version: { textAlign: "center", marginTop: 16, fontSize: 12 },
  tabBar: { flexDirection: "row", borderTopWidth: 1, paddingTop: 9 },
  tab: { flex: 1, minHeight: 48, alignItems: "center", justifyContent: "center", gap: 4 },
  tabText: { fontSize: 10, fontWeight: "600" },
  modalHost: { flex: 1 },
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    padding: 20,
    backgroundColor: "rgba(0,0,0,0.32)",
  },
  modal: {
    flex: 1,
    ...Platform.select({
      web: {
        width: "100%",
        maxWidth: 720,
        maxHeight: "92%",
        alignSelf: "center",
        marginVertical: 24,
        borderRadius: 24,
        borderWidth: 1,
        overflow: "hidden",
      },
      default: {},
    }),
  },
  keyboardAvoidingModal: { flex: 1 },
  authModalOverlay: {
    flex: 1,
    justifyContent: "center",
    padding: Platform.select({ web: 20, default: 0 }),
  },
  authModalPanel: {
    flex: 1,
    width: "100%",
    overflow: "hidden",
    ...Platform.select({
      web: {
        maxWidth: 560,
        maxHeight: "92%",
        alignSelf: "center",
        borderRadius: 22,
        borderWidth: 1,
      },
      default: {},
    }),
  },
  authBrand: { alignItems: "center", gap: 8, marginBottom: 8 },
  authLogo: { width: 64, height: 64, borderRadius: 16 },
  authBrandTitle: { fontSize: 20, fontWeight: "800" },
  modalHeader: {
    flexDirection: "row",
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 16,
    alignItems: "center",
    justifyContent: "space-between",
  },
  cancel: { fontSize: 16, fontWeight: "600" },
  modalTitle: { fontSize: 18, fontWeight: "700" },
  modalCloseButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  form: { padding: 20, gap: 12 },
  keyboardAwareForm: { paddingBottom: 128 },
  formLabel: { fontSize: 12, fontWeight: "700", letterSpacing: 0.8, marginTop: 7 },
  inputGroup: { borderRadius: 14, borderWidth: 1, overflow: "hidden" },
  input: { fontSize: 16, padding: 15, minHeight: 50 },
  inputNoOutline: Platform.select<TextStyle>({
    web: { outlineWidth: 0 },
    default: {},
  }),
  passwordInputRow: { flexDirection: "row", alignItems: "center" },
  passwordInput: { flex: 1 },
  passwordToggle: { width: 50, minHeight: 50, alignItems: "center", justifyContent: "center" },
  priceInput: { flexDirection: "row", alignItems: "center" },
  currency: { fontSize: 16, paddingLeft: 15 },
  presetSearchGroup: {
    minHeight: 48,
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  presetSearchInput: { flex: 1, minHeight: 46, fontSize: 15 },
  presetPickerButton: {
    minHeight: 62,
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  presetSheet: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    maxHeight: "82%",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: Platform.select({ ios: 34, default: 22 }),
    gap: 14,
  },
  presetSheetListScroll: { maxHeight: 420 },
  presetList: { gap: 10, paddingRight: 2 },
  presetRow: {
    height: 64,
    width: "100%",
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  presetIcon: { width: 34, height: 34, borderRadius: 999, alignItems: "center", justifyContent: "center" },
  presetIconText: { color: "#fff", fontSize: 12, fontWeight: "800" },
  presetText: { fontSize: 14, fontWeight: "700" },
  presetCategory: { fontSize: 12, fontWeight: "700", marginTop: 2 },
  presetCheckSlot: { width: 20, height: 20, alignItems: "center", justifyContent: "center" },
  periods: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  periodButton: {
    minWidth: 96,
    flexGrow: 1,
    padding: 14,
    alignItems: "center",
    borderRadius: 14,
    borderWidth: 1,
  },
  payDateRow: {
    minHeight: 62,
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  payDateRowIcon: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  payDateRowLabel: { fontSize: 12, fontWeight: "700", letterSpacing: 0.5 },
  payDateRowValue: { fontSize: 16, fontWeight: "700", marginTop: 2 },
  payDateRowMeta: { flexDirection: "row", alignItems: "center", gap: 4 },
  payDateRowDay: { fontSize: 13, fontWeight: "800" },
  payDateTitle: { fontSize: 22, fontWeight: "800", marginTop: 2 },
  payDateSubtitle: { fontSize: 13, marginTop: 4 },
  sheetScrim: { flex: 1, backgroundColor: "rgba(0,0,0,0.32)" },
  dateSheet: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: Platform.select({ ios: 34, default: 22 }),
    gap: 16,
  },
  dateSheetHandle: {
    alignSelf: "center",
    width: 42,
    height: 5,
    borderRadius: 999,
    backgroundColor: "#D1D5DB",
  },
  dateSheetHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 16 },
  doneButton: { minHeight: 40, justifyContent: "center", paddingHorizontal: 4 },
  doneButtonText: { fontSize: 16, fontWeight: "800" },
  dateWheelRow: { flexDirection: "row", gap: 10 },
  dateWheelColumn: { flex: 1, gap: 8 },
  dateWheelLabel: { fontSize: 12, fontWeight: "800", textAlign: "center", letterSpacing: 0.6 },
  dateWheel: { maxHeight: 196 },
  dateWheelItem: { height: 42, borderRadius: 12, alignItems: "center", justifyContent: "center", marginBottom: 6 },
  dateWheelText: { fontSize: 17, fontWeight: "800" },
  visualPanel: { borderWidth: 1, borderRadius: 16, padding: 14, gap: 12 },
  visualPreviewRow: { flexDirection: "row", alignItems: "center", gap: 12 },
  iconBadgeText: { color: "#fff", fontSize: 12, fontWeight: "900" },
  iconChoiceRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  iconChoice: {
    width: 38,
    height: 38,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  symbolSearchGroup: {
    minHeight: 46,
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  symbolSearchInput: { flex: 1, minHeight: 44, fontSize: 15 },
  symbolProviderRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  symbolProviderButton: {
    minHeight: 36,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 11,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  symbolProviderCheckbox: {
    width: 18,
    height: 18,
    borderRadius: 5,
    borderWidth: 1.5,
    alignItems: "center",
    justifyContent: "center",
  },
  symbolProviderText: { fontSize: 12, fontWeight: "800" },
  symbolResultList: { gap: 8, paddingRight: 2 },
  symbolResult: {
    width: 86,
    height: 72,
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 8,
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  symbolResultIcon: {
    width: 28,
    height: 28,
    alignItems: "center",
    justifyContent: "center",
  },
  symbolResultText: { width: "100%", fontSize: 11, fontWeight: "800", textAlign: "center" },
  colorPickerGroup: { gap: 8 },
  colorPickerLabel: { fontSize: 12, fontWeight: "800", letterSpacing: 0.6 },
  colorPickerRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  colorPickerSheet: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: Platform.select({ ios: 34, default: 22 }),
    gap: 16,
  },
  reanimatedColorPicker: { gap: 16 },
  colorPickerPreviewRow: { minHeight: 48 },
  colorPickerPreview: { borderRadius: 14, borderWidth: 1 },
  colorPickerValue: { fontSize: 18, fontWeight: "800" },
  reanimatedPickerBody: { alignItems: "center", gap: 14 },
  colorPickerPanel: { width: "100%", height: 190, borderRadius: 16 },
  colorPickerHueCircular: { width: 220, height: 220 },
  colorPresetSection: { gap: 10 },
  reanimatedSwatches: { gap: 8 },
  reanimatedSwatch: { width: 34, height: 34, borderRadius: 11 },
  colorWheelButton: {
    width: 46,
    height: 46,
    borderRadius: 14,
    borderWidth: 2,
    alignItems: "center",
    justifyContent: "center",
  },
  customBackgroundInput: {
    flex: 1,
    minHeight: 46,
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 12,
    fontSize: 15,
    fontWeight: "700",
  },
  colorSuggestButton: {
    width: 46,
    height: 46,
    borderRadius: 14,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  colorSuggestText: { fontSize: 18, fontWeight: "900" },
  sortSheetHost: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: "center",
    paddingHorizontal: Platform.select({ web: 20, default: 0 }),
  },
  sortSheet: {
    width: "100%",
    maxWidth: Platform.select({ web: 460, default: undefined }),
    borderWidth: Platform.select({ web: 1, default: 0 }),
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderBottomLeftRadius: Platform.select({ web: 24, default: 0 }),
    borderBottomRightRadius: Platform.select({ web: 24, default: 0 }),
    padding: 20,
    paddingBottom: Platform.select({ ios: 34, default: 24 }),
    gap: 14,
  },
  sortSheetTitle: { fontSize: 18, fontWeight: "800" },
  sortOptionList: { gap: 10 },
  sortOption: {
    minHeight: 52,
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  sortOptionText: { flex: 1, fontSize: 15, fontWeight: "700" },
  dateLabel: { fontSize: 12, fontWeight: "700", letterSpacing: 0.8 },
  dateValue: { fontSize: 18, fontWeight: "700", marginTop: 3 },
  categoryGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  errorText: { color: "#DC2626", fontSize: 13 },
  saveArea: { padding: 16, borderTopWidth: 1, gap: 10 },
  saveButton: { height: 50, borderRadius: 14, justifyContent: "center", alignItems: "center" },
  authSaveButton: { borderWidth: 1 },
  saveText: { color: "#fff", fontSize: 16, fontWeight: "700" },
  deleteSubscriptionButton: {
    height: 46,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  deleteSubscriptionText: { color: "#DC2626", fontSize: 15, fontWeight: "700" },
  deleteConfirmRow: { flexDirection: "row", gap: 10 },
  deleteConfirmButton: {
    flex: 1,
    height: 46,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
  },
  deleteConfirmText: { fontSize: 15, fontWeight: "800" },
  syncPromptOverlay: {
    flex: 1,
    justifyContent: "center",
    padding: 20,
    backgroundColor: "rgba(0,0,0,0.36)",
  },
  syncPromptPanel: {
    width: "100%",
    maxWidth: Platform.select({ web: 520, default: 460 }),
    maxHeight: "92%",
    alignSelf: "center",
    borderRadius: 22,
    borderWidth: 1,
    padding: 20,
    gap: 14,
  },
  syncPromptTitle: { fontSize: 21, fontWeight: "800" },
  syncPromptHeaderRow: { minHeight: 36, flexDirection: "row", alignItems: "center", gap: 10 },
  syncPromptHeaderTitle: { flex: 1 },
  syncPromptIconButton: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  syncPromptBody: { fontSize: 14, lineHeight: 20 },
  syncPromptActions: { gap: 10 },
  syncPromptPrimaryButton: {
    minHeight: 62,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    justifyContent: "center",
  },
  syncPromptPrimaryText: { color: "#FFFFFF", fontSize: 16, fontWeight: "800" },
  syncPromptPrimaryMeta: { color: "#DBEAFE", fontSize: 13, fontWeight: "600", marginTop: 3 },
  syncPromptButton: {
    minHeight: 62,
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
    justifyContent: "center",
  },
  syncPromptButtonContent: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 },
  syncPromptButtonText: { fontSize: 16, fontWeight: "800" },
  syncPromptDangerText: { fontSize: 16, fontWeight: "800" },
  syncPromptButtonMeta: { fontSize: 13, fontWeight: "600", marginTop: 3 },
  syncDiffBox: {
    maxHeight: 320,
    borderWidth: 1,
    borderRadius: 14,
    overflow: "hidden",
  },
  syncDiffHeader: {
    minHeight: 36,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: "row",
  },
  syncDiffHeaderText: {
    flex: 1,
    paddingHorizontal: 10,
    paddingVertical: 9,
    fontSize: 12,
    fontWeight: "800",
    textAlign: "center",
  },
  syncDiffRightHeader: { borderLeftWidth: StyleSheet.hairlineWidth },
  syncDiffScroll: { maxHeight: 284 },
  syncDiffContent: { paddingBottom: 1 },
  syncDiffRow: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: "row",
  },
  syncDiffLocalRow: { backgroundColor: "rgba(220,38,38,0.10)" },
  syncDiffDatabaseRow: { backgroundColor: "rgba(22,163,74,0.10)" },
  syncDiffChangedRow: { backgroundColor: "rgba(37,99,235,0.10)" },
  syncDiffCell: {
    flex: 1,
    minWidth: 0,
    paddingHorizontal: 8,
    paddingVertical: 4,
    fontSize: 11,
    lineHeight: 14,
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
  },
  syncDiffDatabaseCell: { borderLeftWidth: StyleSheet.hairlineWidth },
  syncDiffLocalText: { color: "#B91C1C" },
  syncDiffDatabaseText: { color: "#15803D" },
  syncDiffChangedText: { color: "#1D4ED8" },
  syncDiffEmptyBox: { padding: 14, fontSize: 13, lineHeight: 18, textAlign: "center" },
});
