import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safe: { flex: 1 },
  loading: { flex: 1, alignItems: "center", justifyContent: "center", gap: 12 },
  loadingText: { fontSize: 14 },
  shell: { flex: 1, alignSelf: "center", width: "100%", maxWidth: 680 },
  content: { flex: 1 },
  screen: { padding: 20, paddingBottom: 36, gap: 12 },
  topRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 12 },
  greeting: { fontSize: 14, fontWeight: "500", marginBottom: 3 },
  title: { fontSize: 28, fontWeight: "700", letterSpacing: -0.5 },
  addCircle: { width: 44, height: 44, borderRadius: 14, alignItems: "center", justifyContent: "center" },
  totalCard: { borderRadius: 22, padding: 20, marginBottom: 8 },
  totalEyebrow: { color: "#BFDBFE", fontSize: 12, fontWeight: "700", letterSpacing: 1 },
  total: { color: "#fff", fontSize: 36, fontWeight: "700", letterSpacing: -1, marginTop: 8 },
  totalFooter: { flexDirection: "row", justifyContent: "space-between", marginTop: 17, alignItems: "center" },
  totalSub: { color: "#DBEAFE", fontSize: 13 },
  totalYearly: { color: "#fff", fontSize: 13, fontWeight: "600" },
  sectionHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 13, marginBottom: 1 },
  sectionTitle: { fontSize: 18, fontWeight: "700" },
  sectionAction: { fontSize: 14, fontWeight: "600" },
  card: { borderWidth: 1, borderRadius: 18, overflow: "hidden" },
  subscriptionStack: { gap: 12 },
  spendingPill: {
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 13,
    marginTop: 2,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  spendingPillLabel: { fontSize: 12, fontWeight: "800", letterSpacing: 0.6, textTransform: "uppercase" },
  spendingPillValue: { fontSize: 17, fontWeight: "800" },
  spendingPillMeta: { fontSize: 13, fontWeight: "600" },
  renewalRow: {
    minHeight: 74,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 12,
    borderRadius: 14,
  },
  subscriptionRow: {
    minHeight: 74,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 12,
    borderRadius: 14,
  },
  lastSubscriptionPill: { marginBottom: 0 },
  iconBadge: { width: 44, height: 44, borderRadius: 13, alignItems: "center", justifyContent: "center" },
  rowText: { flex: 1 },
  rowName: { fontSize: 16, fontWeight: "600" },
  rowMeta: { fontSize: 13, marginTop: 3 },
  rowPrice: { fontSize: 15, fontWeight: "700", textAlign: "right" },
  priceStack: { alignItems: "flex-end" },
  renewalStatus: { fontSize: 12, marginTop: 4 },
  removeButton: { marginLeft: 3, padding: 4 },
  removeConfirmActions: { flexDirection: "row", gap: 4, marginLeft: 3 },
  removeConfirmButton: { padding: 4 },
  summary: { flexDirection: "row", gap: 10, alignItems: "center", padding: 15, borderRadius: 16, marginTop: 8 },
  summaryText: { fontSize: 13, flex: 1, lineHeight: 18 },
  chips: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 4 },
  chip: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 999 },
  chipText: { fontSize: 14, fontWeight: "600" },
  empty: { alignItems: "center", padding: 28, borderWidth: 1, borderRadius: 18 },
  emptyTitle: { fontSize: 17, fontWeight: "700", marginTop: 12 },
  emptyText: { textAlign: "center", fontSize: 14, lineHeight: 20, marginTop: 6 },
  emptyButton: { marginTop: 18, paddingHorizontal: 16, height: 42, justifyContent: "center", borderRadius: 12 },
  emptyButtonText: { color: "#fff", fontWeight: "700" },
  metricGrid: { flexDirection: "row", gap: 12, marginTop: 12, marginBottom: 10 },
  metric: { flex: 1, borderWidth: 1, borderRadius: 18, padding: 16 },
  metricLabel: { fontSize: 13 },
  metricValue: { fontSize: 21, fontWeight: "700", marginTop: 7 },
  barRow: { padding: 15, gap: 9 },
  barTitle: { flexDirection: "row", justifyContent: "space-between" },
  barName: { fontSize: 15, fontWeight: "600" },
  barPrice: { fontSize: 14 },
  barTrack: { height: 7, borderRadius: 99, overflow: "hidden" },
  barFill: { height: "100%", borderRadius: 99 },
  calendarCard: { padding: 12, gap: 10 },
  calendarHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  calendarMonth: { flex: 1, fontSize: 15, fontWeight: "800", textAlign: "center" },
  calendarArrowButton: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  calendarWeekHeader: { flexDirection: "row", gap: 6 },
  calendarWeekday: { flex: 1, fontSize: 11, fontWeight: "800", textAlign: "center" },
  calendarGrid: { gap: 6 },
  calendarWeek: { flexDirection: "row", gap: 6 },
  calendarDay: {
    flex: 1,
    minHeight: 76,
    borderWidth: 1,
    borderRadius: 10,
    padding: 5,
    gap: 4,
  },
  calendarSelectedDay: { borderWidth: 2, padding: 4 },
  calendarDayNumber: { fontSize: 11, fontWeight: "800" },
  calendarCountBadge: {
    minWidth: 24,
    height: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    marginTop: 9,
    paddingHorizontal: 6,
  },
  calendarCountText: { color: "#FFFFFF", fontSize: 12, fontWeight: "800" },
  calendarSelection: { borderTopWidth: 1, paddingTop: 12, gap: 10 },
  calendarSelectionTitle: { fontSize: 15, fontWeight: "800" },
  calendarSelectionEmpty: { fontSize: 13, fontWeight: "600" },
  calendarSubscriptionRow: {
    minHeight: 64,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 10,
    borderRadius: 14,
  },
  calendarSubscriptionAccent: { width: 5, alignSelf: "stretch", borderRadius: 99 },
  calendarSubscriptionName: { fontSize: 15, fontWeight: "700" },
  calendarSubscriptionMeta: { fontSize: 13, marginTop: 3 },
  calendarSubscriptionPrice: { fontSize: 15, fontWeight: "800", textAlign: "right" },
  settingsLabel: { marginTop: 12, marginBottom: -2, fontSize: 12, fontWeight: "700", letterSpacing: 0.8 },
  settingRow: { flexDirection: "row", padding: 15, gap: 12, alignItems: "center" },
  settingOption: { padding: 15, gap: 12 },
  accountHeader: { flexDirection: "row", alignItems: "center", gap: 12 },
  authButtons: { flexDirection: "row", gap: 10 },
  authButton: { flex: 1, minHeight: 44, borderRadius: 12, alignItems: "center", justifyContent: "center", paddingHorizontal: 12 },
  authButtonText: { fontSize: 14, fontWeight: "700", textAlign: "center" },
  primaryButtonText: { color: "#fff", fontSize: 14, fontWeight: "700", textAlign: "center" },
  textButton: { alignSelf: "center", minHeight: 32, justifyContent: "center", paddingHorizontal: 10 },
  textButtonText: { fontSize: 14, fontWeight: "700" },
  statusText: { fontSize: 13, lineHeight: 18 },
  statusPill: { alignSelf: "flex-start", borderRadius: 999, paddingHorizontal: 10, paddingVertical: 5, marginTop: 2 },
  statusPillText: { fontSize: 12, fontWeight: "700" },
  syncButton: {
    minHeight: 44,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 14,
  },
  syncButtonText: { fontSize: 14, fontWeight: "800" },
  comingSoon: { fontSize: 12, fontWeight: "600" },
  paydayInput: { minHeight: 46, borderRadius: 12, paddingHorizontal: 14, fontSize: 16, fontWeight: "700" },
  colorPresetGrid: { flexDirection: "row", flexWrap: "wrap", gap: 9 },
  settingsColorPreset: {
    width: 36,
    height: 36,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  colorPresetInputRow: { flexDirection: "row", gap: 10 },
  colorPresetInput: {
    flex: 1,
    minHeight: 44,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 12,
    fontSize: 15,
    fontWeight: "700",
  },
  colorPresetAddButton: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  reminderTimeRow: {
    minHeight: 46,
    borderRadius: 12,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  reminderTimeInput: { flex: 1, minHeight: 46, fontSize: 16, fontWeight: "700" },
  dangerRow: { flexDirection: "row", gap: 12, padding: 16, borderRadius: 18, borderWidth: 1, alignItems: "center" },
  dangerText: { color: "#DC2626", fontSize: 16, fontWeight: "600" },
  version: { textAlign: "center", marginTop: 16, fontSize: 12 },
  tabBar: { flexDirection: "row", borderTopWidth: 1, paddingTop: 9 },
  tab: { flex: 1, minHeight: 48, alignItems: "center", justifyContent: "center", gap: 4 },
  tabText: { fontSize: 10, fontWeight: "600" },
  modal: { flex: 1 },
  modalHeader: { flexDirection: "row", padding: 20, alignItems: "center", justifyContent: "space-between" },
  cancel: { fontSize: 16, fontWeight: "600" },
  modalTitle: { fontSize: 17, fontWeight: "700" },
  form: { padding: 20, gap: 12 },
  formLabel: { fontSize: 12, fontWeight: "700", letterSpacing: 0.8, marginTop: 7 },
  inputGroup: { borderRadius: 14, borderWidth: 1, overflow: "hidden" },
  input: { fontSize: 16, padding: 15, minHeight: 50 },
  priceInput: { flexDirection: "row", alignItems: "center" },
  currency: { fontSize: 16, paddingLeft: 15 },
  presetSearchGroup: {
    minHeight: 48,
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  presetSearchInput: { flex: 1, minHeight: 46, fontSize: 15 },
  presetPickerButton: {
    minHeight: 62,
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  presetSheet: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    maxHeight: "82%",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: Platform.select({ ios: 34, default: 22 }),
    gap: 14,
  },
  presetSheetListScroll: { maxHeight: 420 },
  presetList: { gap: 10, paddingRight: 2 },
  presetRow: {
    height: 64,
    width: "100%",
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  presetIcon: { width: 34, height: 34, borderRadius: 999, alignItems: "center", justifyContent: "center" },
  presetIconText: { color: "#fff", fontSize: 12, fontWeight: "800" },
  presetText: { fontSize: 14, fontWeight: "700" },
  presetCategory: { fontSize: 12, fontWeight: "700", marginTop: 2 },
  presetCheckSlot: { width: 20, height: 20, alignItems: "center", justifyContent: "center" },
  periods: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  periodButton: {
    minWidth: 96,
    flexGrow: 1,
    padding: 14,
    alignItems: "center",
    borderRadius: 14,
    borderWidth: 1,
  },
  payDateRow: {
    minHeight: 62,
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  payDateRowIcon: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  payDateRowLabel: { fontSize: 12, fontWeight: "700", letterSpacing: 0.5 },
  payDateRowValue: { fontSize: 16, fontWeight: "700", marginTop: 2 },
  payDateRowMeta: { flexDirection: "row", alignItems: "center", gap: 4 },
  payDateRowDay: { fontSize: 13, fontWeight: "800" },
  payDateTitle: { fontSize: 22, fontWeight: "800", marginTop: 2 },
  payDateSubtitle: { fontSize: 13, marginTop: 4 },
  sheetScrim: { flex: 1, backgroundColor: "rgba(0,0,0,0.32)" },
  dateSheet: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: Platform.select({ ios: 34, default: 22 }),
    gap: 16,
  },
  dateSheetHandle: {
    alignSelf: "center",
    width: 42,
    height: 5,
    borderRadius: 999,
    backgroundColor: "#D1D5DB",
  },
  dateSheetHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 16 },
  doneButton: { minHeight: 40, justifyContent: "center", paddingHorizontal: 4 },
  doneButtonText: { fontSize: 16, fontWeight: "800" },
  dateWheelRow: { flexDirection: "row", gap: 10 },
  dateWheelColumn: { flex: 1, gap: 8 },
  dateWheelLabel: { fontSize: 12, fontWeight: "800", textAlign: "center", letterSpacing: 0.6 },
  dateWheel: { maxHeight: 196 },
  dateWheelItem: { height: 42, borderRadius: 12, alignItems: "center", justifyContent: "center", marginBottom: 6 },
  dateWheelText: { fontSize: 17, fontWeight: "800" },
  visualPanel: { borderWidth: 1, borderRadius: 16, padding: 14, gap: 12 },
  visualPreviewRow: { flexDirection: "row", alignItems: "center", gap: 12 },
  iconBadgeText: { color: "#fff", fontSize: 12, fontWeight: "900" },
  iconChoiceRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  iconChoice: {
    width: 38,
    height: 38,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  symbolSearchGroup: {
    minHeight: 46,
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  symbolSearchInput: { flex: 1, minHeight: 44, fontSize: 15 },
  symbolProviderRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  symbolProviderButton: {
    minHeight: 32,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 11,
    alignItems: "center",
    justifyContent: "center",
  },
  symbolProviderText: { fontSize: 12, fontWeight: "800" },
  symbolResultList: { gap: 8, paddingRight: 2 },
  symbolResult: {
    width: 86,
    height: 72,
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 8,
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  symbolResultIcon: {
    width: 28,
    height: 28,
    alignItems: "center",
    justifyContent: "center",
  },
  symbolResultText: { width: "100%", fontSize: 11, fontWeight: "800", textAlign: "center" },
  colorPickerGroup: { gap: 8 },
  colorPickerLabel: { fontSize: 12, fontWeight: "800", letterSpacing: 0.6 },
  colorPickerRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  colorPickerSheet: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: Platform.select({ ios: 34, default: 22 }),
    gap: 16,
  },
  colorWheel: { gap: 8 },
  colorWheelRow: { flexDirection: "row", gap: 8 },
  colorWheelCell: {
    flex: 1,
    height: 32,
    borderRadius: 10,
    borderWidth: 2,
  },
  colorWheelButton: {
    width: 46,
    height: 46,
    borderRadius: 14,
    borderWidth: 2,
    alignItems: "center",
    justifyContent: "center",
  },
  customBackgroundInput: {
    flex: 1,
    minHeight: 46,
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 12,
    fontSize: 15,
    fontWeight: "700",
  },
  colorSuggestButton: {
    width: 46,
    height: 46,
    borderRadius: 14,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  colorSuggestText: { fontSize: 18, fontWeight: "900" },
  dateLabel: { fontSize: 12, fontWeight: "700", letterSpacing: 0.8 },
  dateValue: { fontSize: 18, fontWeight: "700", marginTop: 3 },
  categoryGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  errorText: { color: "#DC2626", fontSize: 13 },
  saveArea: { padding: 16, borderTopWidth: 1, gap: 10 },
  saveButton: { height: 50, borderRadius: 14, justifyContent: "center", alignItems: "center" },
  saveText: { color: "#fff", fontSize: 16, fontWeight: "700" },
  deleteSubscriptionButton: {
    height: 46,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  deleteSubscriptionText: { color: "#DC2626", fontSize: 15, fontWeight: "700" },
  deleteConfirmRow: { flexDirection: "row", gap: 10 },
  deleteConfirmButton: {
    flex: 1,
    height: 46,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
  },
  deleteConfirmText: { fontSize: 15, fontWeight: "800" },
});
