import { categories } from "./constants";

export type SubscriptionPreset = {
  name: string;
  category: (typeof categories)[number];
  simpleIconSlug: string;
  iconLabel: string;
  iconColor: string;
  backgroundColor: string;
};

function preset(
  name: string,
  category: SubscriptionPreset["category"],
  simpleIconSlug: string,
  iconLabel: string,
  iconColor: string,
  backgroundColor: string,
): SubscriptionPreset {
  return { name, category, simpleIconSlug, iconLabel, iconColor, backgroundColor };
}

export const subscriptionPresets: SubscriptionPreset[] = [
  preset("1Password", "Software", "1password", "1P", "#3B66BC", "#EAF0FB"),
  preset("Netflix", "Streaming", "netflix", "N", "#E50914", "#FDE8EA"),
  preset("Spotify", "Music", "spotify", "S", "#1DB954", "#E8F8EF"),
  preset("YouTube Premium", "Streaming", "youtube", "Y", "#FF0000", "#FFE7E7"),
  preset("Disney+", "Streaming", "disneyplus", "D+", "#113CCF", "#E9EDFF"),
  preset("Prime Video", "Streaming", "primevideo", "P", "#00A8E1", "#E5F7FD"),
  preset("Apple TV+", "Streaming", "appletv", "TV", "#111111", "#ECECEC"),
  preset("Apple Music", "Music", "applemusic", "AM", "#FA243C", "#FEE9EC"),
  preset("Hulu", "Streaming", "hulu", "H", "#1CE783", "#E8FCF2"),
  preset("Max", "Streaming", "max", "M", "#002BE7", "#E7EAFF"),
  preset("Paramount+", "Streaming", "paramountplus", "P+", "#0064FF", "#E7F0FF"),
  preset("Peacock", "Streaming", "peacock", "P", "#000000", "#F2F2F2"),
  preset("Crunchyroll", "Streaming", "crunchyroll", "C", "#F47521", "#FEF0E8"),
  preset("AMC+", "Streaming", "amc", "A", "#000000", "#F2F2F2"),
  preset("Discovery+", "Streaming", "discovery", "D+", "#0B5DAB", "#E8F1FA"),
  preset("Audible", "Education", "audible", "A", "#F8991C", "#FFF3E2"),
  preset("Kindle", "Education", "amazonkindle", "K", "#00A4B8", "#E5F8FA"),
  preset("Amazon Prime", "Utilities", "amazonprime", "P", "#00A8E1", "#E5F7FD"),
  preset("Amazon Music", "Music", "amazonmusic", "AM", "#25D1DA", "#E9FAFB"),
  preset("Amazon AWS", "Cloud", "amazonaws", "AWS", "#FF9900", "#FFF3E0"),
  preset("Adobe Creative Cloud", "Software", "adobecreativecloud", "CC", "#DA1F26", "#FCE9EA"),
  preset("Adobe Firefly", "Software", "adobe", "A", "#FF0000", "#FFE7E7"),
  preset("Canva", "Software", "canva", "C", "#00C4CC", "#E5FAFB"),
  preset("Figma", "Software", "figma", "F", "#F24E1E", "#FEEDE8"),
  preset("Notion", "Software", "notion", "N", "#000000", "#F2F2F2"),
  preset("Slack", "Software", "slack", "S", "#4A154B", "#F1E8F1"),
  preset("Asana", "Software", "asana", "A", "#F06A6A", "#FDEDED"),
  preset("Todoist", "Software", "todoist", "T", "#E44332", "#FCECE9"),
  preset("Trello", "Software", "trello", "T", "#0052CC", "#E7EFFA"),
  preset("Jira", "Software", "jira", "J", "#0052CC", "#E7EFFA"),
  preset("Linear", "Software", "linear", "L", "#5E6AD2", "#EFF0FB"),
  preset("Zoom", "Software", "zoom", "Z", "#0B5CFF", "#E8EFFF"),
  preset("Grammarly", "Software", "grammarly", "G", "#15C39A", "#E8F9F5"),
  preset("Evernote", "Software", "evernote", "E", "#00A82D", "#E5F6EA"),
  preset("Obsidian", "Software", "obsidian", "O", "#7C3AED", "#F2ECFE"),
  preset("Raycast", "Software", "raycast", "R", "#FF6363", "#FFEEEE"),
  preset("Setapp", "Software", "setapp", "S", "#E6C141", "#FCF7E6"),
  preset("Cursor", "Software", "cursor", "C", "#000000", "#F2F2F2"),
  preset("ChatGPT", "Software", "openai", "AI", "#10A37F", "#E7F6F2"),
  preset("Claude", "Software", "anthropic", "C", "#D97757", "#FBF0EC"),
  preset("GitHub", "Software", "github", "GH", "#181717", "#ECECEC"),
  preset("GitLab", "Software", "gitlab", "GL", "#FC6D26", "#FEF0E9"),
  preset("Bitbucket", "Software", "bitbucket", "B", "#0052CC", "#E7EFFA"),
  preset("Cloudflare", "Cloud", "cloudflare", "CF", "#F38020", "#FEF1E8"),
  preset("Dropbox", "Cloud", "dropbox", "D", "#0061FF", "#E7F0FF"),
  preset("Google One", "Cloud", "googleone", "G", "#4285F4", "#EBF3FE"),
  preset("Microsoft 365", "Software", "microsoft", "MS", "#5E5E5E", "#F0F0F0"),
  preset("iCloud", "Cloud", "icloud", "iC", "#3693F3", "#EAF4FE"),
  preset("OneDrive", "Cloud", "microsoftonedrive", "OD", "#0078D4", "#E7F2FB"),
  preset("Box", "Cloud", "box", "B", "#0061D5", "#E7F0FB"),
  preset("Backblaze", "Cloud", "backblaze", "B", "#E21E29", "#FCE9EA"),
  preset("Xbox Game Pass", "Gaming", "xbox", "X", "#107C10", "#E7F2E7"),
  preset("PlayStation Plus", "Gaming", "playstation", "PS", "#003791", "#E7ECF4"),
  preset("Nintendo Switch Online", "Gaming", "nintendoswitch", "NS", "#E60012", "#FDE7E9"),
  preset("Discord Nitro", "Gaming", "discord", "D", "#5865F2", "#EEF0FE"),
  preset("Twitch", "Streaming", "twitch", "T", "#9146FF", "#F4EDFF"),
  preset("OpenAI", "Software", "openai", "AI", "#412991", "#EEEAF8"),
  preset("NordVPN", "Utilities", "nordvpn", "N", "#4687FF", "#ECF3FF"),
  preset("Proton VPN", "Utilities", "protonvpn", "PV", "#6D4AFF", "#F0EDFF"),
  preset("Proton Mail", "Utilities", "protonmail", "PM", "#6D4AFF", "#F0EDFF"),
  preset("1Password Families", "Software", "1password", "1P", "#3B66BC", "#EAF0FB"),
  preset("Bitwarden", "Software", "bitwarden", "B", "#175DDC", "#E8EFFC"),
  preset("Dashlane", "Software", "dashlane", "D", "#0E353D", "#E7EBEC"),
  preset("LastPass", "Software", "lastpass", "LP", "#D32D27", "#FBEAE9"),
  preset("Keeper", "Software", "keeper", "K", "#FFC700", "#FFF8D9"),
  preset("Coursera", "Education", "coursera", "C", "#0056D2", "#E7EFFE"),
  preset("Brilliant", "Education", "brilliant", "B", "#FF6F00", "#FFF0E2"),
  preset("Skillshare", "Education", "skillshare", "S", "#00FF84", "#E5FFF3"),
  preset("MasterClass", "Education", "masterclass", "MC", "#D30000", "#FBE6E6"),
  preset("Duolingo", "Education", "duolingo", "D", "#58CC02", "#EEFBE6"),
  preset("Strava", "Fitness", "strava", "S", "#FC4C02", "#FEEDE5"),
  preset("Peloton", "Fitness", "peloton", "P", "#181A1D", "#ECEDEE"),
  preset("MyFitnessPal", "Fitness", "myfitnesspal", "M", "#0066EE", "#E7F0FD"),
  preset("Headspace", "Fitness", "headspace", "H", "#F47D31", "#FEF1EA"),
  preset("Calm", "Fitness", "calm", "C", "#5D9CEC", "#EFF6FE"),
  preset("Patreon", "Finance", "patreon", "P", "#000000", "#F2F2F2"),
  preset("Revolut", "Finance", "revolut", "R", "#191C1F", "#ECEDEE"),
  preset("Wise", "Finance", "wise", "W", "#9FE870", "#F1FCE9"),
  preset("QuickBooks", "Finance", "quickbooks", "QB", "#2CA01C", "#EAF6E8"),
  preset("Xero", "Finance", "xero", "X", "#13B5EA", "#E8F8FD"),
  preset("Shopify", "Finance", "shopify", "S", "#7AB55C", "#EFF7EB"),
  preset("Squarespace", "Utilities", "squarespace", "SQ", "#000000", "#F2F2F2"),
  preset("Webflow", "Software", "webflow", "W", "#146EF5", "#E8F1FE"),
  preset("Wix", "Utilities", "wix", "W", "#0C6EFC", "#E7F0FF"),
  preset("Mailchimp", "Utilities", "mailchimp", "MC", "#FFE01B", "#FFFBD8"),
  preset("LinkedIn Premium", "Utilities", "linkedin", "in", "#0A66C2", "#E7F0F9"),
  preset("X Premium", "Utilities", "x", "X", "#000000", "#F2F2F2"),
  preset("Uber One", "Utilities", "uber", "U", "#000000", "#F2F2F2"),
  preset("Grubhub+", "Utilities", "grubhub", "G", "#FF8000", "#FFF2E5"),
  preset("Instacart+", "Utilities", "instacart", "I", "#43B02A", "#ECF7E9"),
];
